### ISSUE TITLE
NPE on recursive search

### ISSUE THREAD

**Issue by GoogleCodeExporter** [AlejandroJL/mp4parser#61]
```
When I run List<AudioSampleEntry> boxes = 
isoFile.getMovieBox()   .getBoxes(AudioSampleEntry.class, true);

I get: 

Caused by: java.lang.NullPointerException
 at java.util.ArrayList.addAll(ArrayList.java:184)
 at com.googlecode.mp4parser.AbstractContainerBox.getBoxes(AbstractContainerBox.java:83)
 at com.googlecode.mp4parser.AbstractContainerBox.getBoxes(AbstractContainerBox.java:83)
```

Original issue reported on code.google.com by `freemp3d...@gmail.com` on 7 May 2013 at 10:54

**Comment by GoogleCodeExporter** [comment]
```
Sorry for coming back so late to this but generally this line of code works. It 
might in your special case that it is not working. You will need to provide me 
with a fully (not-)working example so I can reproduce the problem
```

Original comment by `Sebastian.Annies` on 30 Jun 2013 at 7:05
