### ISSUE TITLE
NullPointerException in MovieCreator.build

### ISSUE THREAD

**Issue by GoogleCodeExporter** [AlejandroJL/mp4parser#91]
```
I have Android app which uses mp4parser 1.0.2-SNAPSHOT for reading files. I am 
receiving the following crash reports from some devices:

java.lang.NullPointerException
       at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(SourceFile:48)
       at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(SourceFile:35)
       at ru.roadar.android.audio.Mp4ParserAudioMuxer.mux(SourceFile:57)
       at ru.roadar.android.video.VideoRecorder$VideoAudioMuxer.run(SourceFile:641)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

In fact, it's possible for IsoFile.getMovieBox to return NULL, so it may be 
makes sense to add a guard against it.
```

Original issue reported on code.google.com by `andrey.c...@gmail.com` on 9 Jun 2014 at 8:36

**Comment by GoogleCodeExporter** [comment]
```
Well, no MP4 file might ever have no moov. 
If it doesn't have moov it's not an MP4. You most likely didn't compile the 
aspects
```

Original comment by `Sebastian.Annies` on 19 Jun 2014 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
I have the same error. 
It occurs when I press continuously pause and resume button.
But I checked file path and file size, they are both != null.
What should I do?
this is log
java.lang.NullPointerException: Attempt to invoke virtual method 
'java.util.List com.coremedia.iso.boxes.MovieBox.getBoxes(java.lang.Class)' on 
a null object reference
01-09 07:01:22.889 W       9298     System.err                                  
                                        at 
com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator
.java:48)
```

Original comment by `thutrang...@gmail.com` on 14 Feb 2015 at 4:52
